### ISSUE TITLE
Doesn't work with jQuery 3.4.1 slim

### ISSUE THREAD

**Issue by hydraheim** [wookchu/SimpleTab#1]
The regular version works. However, the slim version (this one was tested https://code.jquery.com/jquery-3.4.1.slim.min.js) does not. 

**Here's the log:**

```
jQuery.Deferred exception: m(...).fadeIn is not a function h@http://localhost:8765/js/simpletab.min.js:1:994
m.fn.simpleTab/</<@http://localhost:8765/js/simpletab.min.js:1:2547
m.fn.simpleTab/<@http://localhost:8765/js/simpletab.min.js:1:2556
each@https://code.jquery.com/jquery-3.4.1.slim.min.js:2:2981
each@https://code.jquery.com/jquery-3.4.1.slim.min.js:2:1623
m.fn.simpleTab@http://localhost:8765/js/simpletab.min.js:1:1630
e@https://code.jquery.com/jquery-3.4.1.slim.min.js:2:29657
l/</t<@https://code.jquery.com/jquery-3.4.1.slim.min.js:2:29959
```

This looks like an issue with slim not including any animation effects. You should add a fallback if this method is not present.

**Comment by wookchu** [comment]
Thanks for your feedback! This issue is fixed just now and released.
